/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:337376:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield1:337376:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:261821:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button1:261821:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  textfield1 = new GTextField(this, 681, 400, 134, 30, G4P.SCROLLBARS_NONE);
  textfield1.setText("Username");
  textfield1.setPromptText("Username");
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  label1 = new GLabel(this, 680, 352, 133, 32);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Insert Username :)");
  label1.setOpaque(false);
  button1 = new GButton(this, 709, 445, 80, 30);
  button1.setText("Save");
  button1.addEventHandler(this, "button1_click1");
}

// Variable declarations 
// autogenerated do not edit
GTextField textfield1; 
GLabel label1; 
GButton button1; 
